### PR TITLE
add linestyle

### PR DESCRIPTION
**Pull request by bkamins**
Adds `linestyle` option to `plot` and `plot!`. Line style is following Gnuplot 5 and is a string allowing: space ` `, dot `.`, dash `-` and underline `_` characters.

### CODE REVIEW

**Comment by mbaz** [comment]
Thanks a lot -- I've been busy these past week but I hope to take a look at this and your other issues/PRs soon. If you have the time, it'd be great if you could look into the failing checks and also add tests and/or documentation for new features.

**Comment by bkamins** [comment]
Sure.
I believe the checks fail because Travis is set to 0.5, but I have changed it in PR #67 (a more complete change of Travis build was proposed in #65) and I did not want to duplicate it to avoid PR merge problems.

**Comment by bkamins** [comment]
I have added some documentation and squashed commits.

**Comment by CarloLucibello** [comment]
some indentation problems and needs rebase, otherwise looks good!

**Comment by bkamins** [comment]
Rebased and fixed overlong lines (I initially left them because in other places in code there were also overlong lines).

As for indentation - you use mixed style - sometimes tab is used for indent and sometimes space - even in the same file. I used spaces everywhere, but I am not sure about your intention.
I propose to change all tabs to spaces in whole code of the package using the standard convention *one tab => 4 spaces*. Do you want me to do it?

**Comment by mbaz** [comment]
@bkamins I have converted all tabs to spaces in my local branch. Thanks!

**Comment by mbaz** [comment]
Please correct me if I'm wrong, but wouldn't `dashtype` (instead of `linestyle`) be a better name for this?

**Comment by bkamins** [comment]
`linestyle` name is used e.g. in R, Plots.jl, Matplotlib for this effect.
I can change it to `dashtype` if you prefer.
When you decide what is best I will rebase this PR and adjust accordingly to make it ready for merging.

**Comment by mbaz** [comment]
Let's go with `linestyle`. Thanks!

**Comment by bkamins** [comment]
rebased

**Comment by mbaz** [comment]
Thanks!

**Pull request merged**
