### PR TITLE
works with linux/gnuplot-qt

### PR DESCRIPTION
**Pull request by MHellmund**
Only tested  with Linux (debian/testing), julia 0.4.1, gnuplot 5.0p1, so please test&review: 
- gaston_tests() and gaston_demo() run through w/o errors/deprecation warnings
- popen3(): works now with julia.4
- use "qt" backend of gnuplot since for me "wxt" is unstable and segfaults with the many open windows of
  gaston_demo() 
 (this should better depend on the OS?)
- llplot(): removed the "wait for gnuplot to write on stdout"  logic since this blocks forever in Linux
 (presumably a buffering problem)

### CODE REVIEW

**Comment by mbaz** [comment]
Thank you. I'll take a closer look but it seems good.

The logic for waiting for gnuplot to respond works in julia 0.3, but not in
0.4, and I haven't had time to look into it.

I need to come up with a way to allow the user to set their default
terminal on startup. Wxt works for me, you prefer qt, on Mac aquaterm
doesn't work, and so on.

**Comment by mbaz** [comment]
I'm tempted to set the default term to X11, since it should work in every
system, and let the user change that after loading the package if they want.

**Comment by mbaz** [comment]
I divided your pull request into simpler changes and pushed them to master.
It passes all tests and the demo runs fine. The only change I haven't done
yet is regarding the default terminal. Again, thanks for contributing!

**Comment by MHellmund** [comment]
Thanks! So feel free to close my pull request.
Another note: 
demo #11 (dots plotstyle) doesn't work properly for me. It plots only the red point,
not the blue ones. 

Regards, Meik


-- 
Meik Hellmund <Meik.Hellmund@math.uni-leipzig.de>

**Comment by mbaz** [comment]
It works for me with wxt terminal... can you try a different terminal?

**Comment by mbaz** [comment]
Another thing you could try is to try to reproduce the problem directly in
gnuplot.

**Comment by MHellmund** [comment]
You are absolutely right. I was bitten by 
http://sourceforge.net/p/gnuplot/bugs/1715/

Regards, Meik

**Pull request closed without merging**
