### PR TITLE
update travis

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by CarloLucibello** [comment]
@mbaz bumpity bump. This and the other open PRs are really short and easy to review

**Comment by CarloLucibello** [comment]
ops, closed by mistake

**Comment by mbaz** [comment]
@CarloLucibello I'm in the middle of a particulary busy period, but I should be able to free some time in the next few days.

**Comment by mbaz** [comment]
@CarloLucibello Why did you comment out the Coveralls and Codecov lines? They're put there by default by `PkgDev.generate`.

**Comment by CarloLucibello** [comment]
yes they are put by default but they are just a stub (e.g. you have `cd(Pkg.dir("dummy")`). If you activate codecov for this repo (in the case you haven't yet) we can set them properly

**Comment by mbaz** [comment]
Got it. Thanks! I never looked too closely at this, TBH, so I'm happy to take your advice.

**Pull request merged**
