### PR TITLE
increase wait time

### PR DESCRIPTION
**Pull request by CarloLucibello**
for gnuplot to finish plot. I needed this when plotting a huge number of points.

### CODE REVIEW

**Comment by mbaz** [comment]
I'm not sure 2000 is a good value. On one hand it will allow for plotting truly huge amounts of data, but on the other hand this means that we'll take 100 seconds to report a true error to the user. I think it's too long. What do you think?

As an aside, does it make sense to plot so many points? Your screen is unlikely to have more than 2000 pixels. Even if you want to zoom in, it might be better to decimate the data before plotting.

**Comment by mbaz** [comment]
What would you think about making this a user-configurable value? That way, if you know you'll be plotting lots of data, you can increase it beforehand, without affecting "normal" plotting with not so much data.

**Comment by CarloLucibello** [comment]
Hi,
in my case I was plotting a lot of points from a simulation, and I could not reduce their number a priori. 
Increasing the limit doesn't effect normale usage, but yes it would take 100 seconds to report a case of true gnuplot unresponsiveness. Did it ever happen to you? When is this supposed to happen?

**Comment by mbaz** [comment]
It happens very infrequently, but it does happen: gnuplot may crash, or the messaging pipes may become disconnected. It's happened to me maybe three or four times in the past few years. However, I want Gaston's design to be as robust as possible.

**Comment by CarloLucibello** [comment]
20 seconds should be enough for my use case. Shall we break a deal to that ? :)

**Comment by mbaz** [comment]
:-D  I like the idea of making it configurable by the user. What do you think about that option?

**Comment by CarloLucibello** [comment]
ok, I'll try to code something

Il giorno ven 26 gen 2018 alle ore 18:01 mbaz <notifications@github.com> ha
scritto:

**Comment by mbaz** [comment]
I have finally implemented adaptive wait time, and it seems to work fine.

**Pull request closed without merging**
